### ISSUE TITLE
官方文档的webhook部分的代码有问题，该更新了

### ISSUE THREAD

**Issue by Jarcis-cy** [chaitin/xray_document#6]
`https://docs.xray.cool/#/scenario/xray_vuln_alert`
代码已经匹配不上xray的输出了

**Comment by virusdefender** [comment]
https://github.com/chaitin/xray/tree/master/webhook 应该是可以用的

**Comment by Jarcis-cy** [comment]
> https://github.com/chaitin/xray/tree/master/webhook 应该是可以用的

我的其实已经改好了，只是说官方文档的参数应该修改一下了，不然其他人直接复制粘贴还是会出问题
